# Generated by Django 5.0.6 on 2024-09-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
